@Clima_API_HostAddress = http://localhost:5239

### Llama al endpoint que devuelve la latitud y longitud
GET {{Clima_API_HostAddress}}/api/v1/weather/echo-location?lat=40.7128&lon=-74.0060
Accept: application/json

###
### Llama al endpoint que obtiene el clima por coordenadas GPS
POST {{Clima_API_HostAddress}}/api/v1/weather/by-gps
Content-Type: application/json

{
  "lat": 34.0522,
  "lon": -118.2437
}

###
### Llama al endpoint que obtiene el pronóstico por día específico
# IMPORTANTE: Cambia "date" a la fecha de MAÑANA (ej. "2025-05-21") para ver resultados.
POST {{Clima_API_HostAddress}}/api/v1/weather/forecast/by-date
Content-Type: application/json

{
  "request": {
    "lat": 34.0522,
    "lon": -118.2437,
    "date": "2026-02-02"
  }
}
